CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE funcionarios (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        nome text NOT NULL,
        email text NOT NULL,
        senha_hash text NOT NULL,
        nivel_acesso text NOT NULL,
        ativo boolean NOT NULL,
        criado_em timestamp NOT NULL,
        CONSTRAINT "PK_funcionarios" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE tarifas (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        valor_minimo numeric NOT NULL,
        valor_incremento numeric NOT NULL,
        minutos_faixa integer NOT NULL,
        data_vigencia timestamp without time zone NOT NULL,
        status text NOT NULL,
        criado_em timestamp NOT NULL,
        CONSTRAINT "PK_tarifas" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE vagas (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        codigo text NOT NULL,
        tipo_vaga text NOT NULL,
        status text NOT NULL,
        posicao_x integer NOT NULL,
        posicao_y integer NOT NULL,
        CONSTRAINT "PK_vagas" PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE auditoria (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        usuario_id integer NOT NULL,
        acao text NOT NULL,
        entidade text NOT NULL,
        entidade_id text NOT NULL,
        dados_antes text,
        dados_depois text,
        resumo text,
        ip text,
        data_hora timestamp NOT NULL,
        CONSTRAINT "PK_auditoria" PRIMARY KEY (id),
        CONSTRAINT "FK_auditoria_funcionarios_usuario_id" FOREIGN KEY (usuario_id) REFERENCES funcionarios (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE reservas (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        vaga_id integer NOT NULL,
        funcionario_id integer NOT NULL,
        status text NOT NULL,
        nome_cliente text NOT NULL,
        telefone_cliente text NOT NULL,
        placa text NOT NULL,
        modelo_veiculo text NOT NULL,
        horario_chegada_previsto timestamp NOT NULL,
        horario_saida_previsto timestamp NOT NULL,
        horario_chegada_real timestamp,
        horario_saida_real timestamp,
        motivo_cancelamento text,
        criado_em timestamp NOT NULL,
        CONSTRAINT "PK_reservas" PRIMARY KEY (id),
        CONSTRAINT "FK_reservas_funcionarios_funcionario_id" FOREIGN KEY (funcionario_id) REFERENCES funcionarios (id) ON DELETE CASCADE,
        CONSTRAINT "FK_reservas_vagas_vaga_id" FOREIGN KEY (vaga_id) REFERENCES vagas (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE TABLE pagamentos (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        reserva_id integer NOT NULL,
        funcionario_id integer NOT NULL,
        tarifa_id integer NOT NULL,
        valor_cobrado numeric NOT NULL,
        forma_pagamento text NOT NULL,
        valor_recebido numeric,
        troco numeric,
        tempo_minutos integer NOT NULL,
        registrado_em timestamp NOT NULL,
        CONSTRAINT "PK_pagamentos" PRIMARY KEY (id),
        CONSTRAINT "FK_pagamentos_funcionarios_funcionario_id" FOREIGN KEY (funcionario_id) REFERENCES funcionarios (id) ON DELETE CASCADE,
        CONSTRAINT "FK_pagamentos_reservas_reserva_id" FOREIGN KEY (reserva_id) REFERENCES reservas (id) ON DELETE CASCADE,
        CONSTRAINT "FK_pagamentos_tarifas_tarifa_id" FOREIGN KEY (tarifa_id) REFERENCES tarifas (id) ON DELETE CASCADE
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_auditoria_usuario_id" ON auditoria (usuario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_pagamentos_funcionario_id" ON pagamentos (funcionario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_pagamentos_reserva_id" ON pagamentos (reserva_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_pagamentos_tarifa_id" ON pagamentos (tarifa_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_reservas_funcionario_id" ON reservas (funcionario_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    CREATE INDEX "IX_reservas_vaga_id" ON reservas (vaga_id);
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260529004259_InitialCreate') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260529004259_InitialCreate', '8.0.0');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;


DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603170942_AddTarifaTipoVaga') THEN
    ALTER TABLE tarifas ADD tipo_vaga text;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260603170942_AddTarifaTipoVaga') THEN
    INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
    VALUES ('20260603170942_AddTarifaTipoVaga', '8.0.0');
    END IF;
END $EF$;
COMMIT;

