// <auto-generated />
using System;
using AutoSlot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AutoSlot.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260603170942_AddTarifaTipoVaga")]
    partial class AddTarifaTipoVaga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AutoSlot.Domain.Models.Auditoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("acao");

                    b.Property<string>("DadosAntes")
                        .HasColumnType("text")
                        .HasColumnName("dados_antes");

                    b.Property<string>("DadosDepois")
                        .HasColumnType("text")
                        .HasColumnName("dados_depois");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("timestamp")
                        .HasColumnName("data_hora");

                    b.Property<string>("Entidade")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade");

                    b.Property<string>("EntidadeId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("entidade_id");

                    b.Property<string>("Ip")
                        .HasColumnType("text")
                        .HasColumnName("ip");

                    b.Property<string>("Resumo")
                        .HasColumnType("text")
                        .HasColumnName("resumo");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("auditoria", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Funcionario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("NivelAcesso")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel_acesso");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("senha_hash");

                    b.HasKey("Id");

                    b.ToTable("funcionarios", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Pagamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FormaPagamento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("forma_pagamento");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer")
                        .HasColumnName("funcionario_id");

                    b.Property<DateTime>("RegistradoEm")
                        .HasColumnType("timestamp")
                        .HasColumnName("registrado_em");

                    b.Property<int>("ReservaId")
                        .HasColumnType("integer")
                        .HasColumnName("reserva_id");

                    b.Property<int>("TarifaId")
                        .HasColumnType("integer")
                        .HasColumnName("tarifa_id");

                    b.Property<int>("TempoMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("tempo_minutos");

                    b.Property<decimal?>("Troco")
                        .HasColumnType("numeric")
                        .HasColumnName("troco");

                    b.Property<decimal>("ValorCobrado")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_cobrado");

                    b.Property<decimal?>("ValorRecebido")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_recebido");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("ReservaId");

                    b.HasIndex("TarifaId");

                    b.ToTable("pagamentos", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Reserva", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em");

                    b.Property<int>("FuncionarioId")
                        .HasColumnType("integer")
                        .HasColumnName("funcionario_id");

                    b.Property<DateTime>("HorarioChegadaPrevisto")
                        .HasColumnType("timestamp")
                        .HasColumnName("horario_chegada_previsto");

                    b.Property<DateTime?>("HorarioChegadaReal")
                        .HasColumnType("timestamp")
                        .HasColumnName("horario_chegada_real");

                    b.Property<DateTime>("HorarioSaidaPrevisto")
                        .HasColumnType("timestamp")
                        .HasColumnName("horario_saida_previsto");

                    b.Property<DateTime?>("HorarioSaidaReal")
                        .HasColumnType("timestamp")
                        .HasColumnName("horario_saida_real");

                    b.Property<string>("ModeloVeiculo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("modelo_veiculo");

                    b.Property<string>("MotivoCancelamento")
                        .HasColumnType("text")
                        .HasColumnName("motivo_cancelamento");

                    b.Property<string>("NomeCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nome_cliente");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("placa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TelefoneCliente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("telefone_cliente");

                    b.Property<int>("VagaId")
                        .HasColumnType("integer")
                        .HasColumnName("vaga_id");

                    b.HasKey("Id");

                    b.HasIndex("FuncionarioId");

                    b.HasIndex("VagaId");

                    b.ToTable("reservas", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp")
                        .HasColumnName("criado_em");

                    b.Property<DateTime>("DataVigencia")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("data_vigencia");

                    b.Property<int>("MinutosFaixa")
                        .HasColumnType("integer")
                        .HasColumnName("minutos_faixa");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoVaga")
                        .HasColumnType("text")
                        .HasColumnName("tipo_vaga");

                    b.Property<decimal>("ValorIncremento")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_incremento");

                    b.Property<decimal>("ValorMinimo")
                        .HasColumnType("numeric")
                        .HasColumnName("valor_minimo");

                    b.HasKey("Id");

                    b.ToTable("tarifas", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Vaga", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<int>("PosicaoX")
                        .HasColumnType("integer")
                        .HasColumnName("posicao_x");

                    b.Property<int>("PosicaoY")
                        .HasColumnType("integer")
                        .HasColumnName("posicao_y");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TipoVaga")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_vaga");

                    b.HasKey("Id");

                    b.ToTable("vagas", (string)null);
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Auditoria", b =>
                {
                    b.HasOne("AutoSlot.Domain.Models.Funcionario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Pagamento", b =>
                {
                    b.HasOne("AutoSlot.Domain.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoSlot.Domain.Models.Reserva", "Reserva")
                        .WithMany()
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoSlot.Domain.Models.Tarifa", "Tarifa")
                        .WithMany()
                        .HasForeignKey("TarifaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Reserva");

                    b.Navigation("Tarifa");
                });

            modelBuilder.Entity("AutoSlot.Domain.Models.Reserva", b =>
                {
                    b.HasOne("AutoSlot.Domain.Models.Funcionario", "Funcionario")
                        .WithMany()
                        .HasForeignKey("FuncionarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AutoSlot.Domain.Models.Vaga", "Vaga")
                        .WithMany()
                        .HasForeignKey("VagaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Vaga");
                });
#pragma warning restore 612, 618
        }
    }
}
